spring.datasource.password=smallcraft
spring.datasource.username=smallcraft
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.url=jdbc:postgresql://localhost:5432/smallcraft?ApplicationName=SmallCraftJpa