title=МПС
id=Код
registrationNumber=№ свидетельства
tailNumber=Бортовой номер
noTailNumber=Без номера
model=Модель(Название)
legalPerson=Юридическое лицо
type=Тип
person=Владелец
boat=Судно
registrationDate=Дата регистрации
pier=Причал
expirationDate=Дата снятия с учета
unit=Подразделение
exportFileName=МПС
serialNumber=Заводской номер
buildYear=Год постройки
notRegistable=Не подлежит регистрации
search=Поиск
expire=Снято с учета
Expirated.EXPIRATED=Снято с учета
Expirated.NOT_EXPIRATED=На учете