id=Код
registrationNumber=№ свидетельства
tailNumber=Бортовой номер
model=Модель(Название)
legalPerson=Юридическое лицо
type=Тип
person=Владелец
boat=Судно
registrationDate=Дата регистрации
pier=Причал
expirationDate=Дата снятия с учета
unit=Подразделение
exportFileName=МПС