FeedbackMessage.CSS.undefined=alert alert-secondary
FeedbackMessage.CSS.debug=alert alert-dark
FeedbackMessage.CSS.info=alert alert-info
FeedbackMessage.CSS.success=alert alert-success
FeedbackMessage.CSS.warning=alert alert-warning
FeedbackMessage.CSS.error=alert alert-danger
FeedbackMessage.CSS.fatal=alert alert-danger
save.error=Ошибка сохранения объекта {0}
save.error.unknown=Неизвестная ошибка сохранения
save.success=Объект {0} успешно сохранен
delete.success=Объект {0} успешно удален
delete.error=Ошибка сохранения объекта {0}
delete=Удалить
close=Закрыть
deleteDialogHeader=Подтвердите удаление записи