id=Код
region=Район
boat=Маломерное плавсредство
activity=Характер деятельности
activities=Характер деятельности
number=Рег номер уведомления
captain=Капитан судна
pier=Причал
btn-captain-eq-owner.true=Капитан и владелец совпадают
btn-captain-eq-owner.false=Капитан и владелец не совпадают
exitCallDateTime=Время звонка на выход
exitDateTime=Время выхода
returnCallDateTime=Время звонка на возвращение
returnDateTime=Время возвращения
filter=Фильтр
do-filter=Фильтровать
clear-filter=Очистить
boat-on-exit=Судно на выходе
exportFileName=Уведомления о выходе(входе)
#========================================
registrationNumber=№ свидетельства
tailNumber=Бортовой номер
model=Модель(Название)
legalPerson=Юридическое лицо
type=Тип
person=Владелец
registrationDate=Дата регистрации
expirationDate=Дата снятия с учета
unit=Подразделение
