id=Код
region=Район
person=Лицо
boat=МПС
date=Дата
dateFrom=Начало
dateTo=Окончание
activity=Характер деятельности
timeOfDay=Время суток
tck=Оборудовано ТСК
year=Год
number=Номер уведомления
captain=Капитан судна