id=Код
region=Район
person=Владелец
boat=Маломерное плавсредство
date=Дата подачи
dateFrom=Начало
dateTo=Окончание
activity=Характер деятельности
timeOfDay=Время суток
tck=Оборудовано ТСК
year=Год
number=Рег.номер
captain=Капитан судна
legalPerson=Юридическое лицо
btn-captain-eq-owner.true=Капитан и владелец совпадают
btn-captain-eq-owner.false=Капитан и владелец не совпадают
exportFileName=Уведомления об осуществлении деятельности
