spring.datasource.password=smallcraft
spring.datasource.username=smallcraft
spring.datasource.url=jdbc:postgresql://192.168.30.10:5432/smallcraft
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.show-sql=true
