home-page-title=Главная страница
boat-page-title=МПС
person-page-title=Физические лица
legal-person-page-title=Юридические лица
notification-page-title=Уведомления о производстве деятельности
exit-notification-page-title=Уведомления о выходе
unit-page-title=Подразделения
dateFormat=dd.MM.yyyy
timeFormat=HH:mm
dateTimeFormat=dd.MM.yyyy HH:mm
createDate=Дата создания
FeedbackMessage.CSS.undefined=alert alert-secondary
FeedbackMessage.CSS.debug=alert alert-dark
FeedbackMessage.CSS.info=alert alert-info
FeedbackMessage.CSS.success=alert alert-success
FeedbackMessage.CSS.warning=alert alert-warning
FeedbackMessage.CSS.error=alert alert-danger
FeedbackMessage.CSS.fatal=alert alert-danger
enableLegalPerson.true=Это юридическое лицо
enableLegalPerson.false=Это физическое лицо
#BOAT
id=Код
registrationNumber=№ свидетельства
tailNumber=Бортовой номер
model=Модель
legalPerson=Юридическое лицо
type=Тип
person=Владелец
boat=Судно
registrationDate=Дата регистрации
pier=Причал
expirationDate=Дата снятия с учета
unit=Подразделение
